# Generated by Django 4.0.1 on 2022-07-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=600, verbose_name='Direccion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('capacity', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.CharField(choices=[('smartphones', 'Smartphones'), ('buds', 'Buds'), ('watch', 'Watch'), ('tablets', 'Tablets'), ('laptops', 'Laptops'), ('pantallas', 'Pantallas'), ('consolas', 'Consolas'), ('monitores', 'Motinotres'), ('case', 'Case'), ('procesador', 'Procesador'), ('motherboard', 'Motherboard'), ('ssd', 'Ssd'), ('hdd', 'Hdd'), ('ram', 'Ram'), ('cooling', 'Cooling'), ('fuente', 'Fuente'), ('mousse', 'Mousse'), ('sillas', 'Sillas'), ('teclados', 'Teclado'), ('lentes', 'Lentes'), ('headsets', 'Headset'), ('mandos', 'Mandos'), ('lavadoras', 'Electrodomesticos'), ('refrigeradoras', 'Muebleria'), ('cocinas', 'Cocinas'), ('camas', 'Camas'), ('taladros', 'Taladros'), ('esmaltes', 'Esmaltes'), ('maquillaje', 'Maquillaje'), ('bicicletas', 'Bicicletas'), ('colchon', 'Colchon')], max_length=20)),
                ('productphoto', models.ImageField(blank=True, null=True, upload_to='shop/catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productos')),
            ],
        ),
    ]
